[package]
name = "obs-scoreboard-assistant"
version = "0.1.0"
authors = ["Christopher S. Corley <cscorley@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
log = "0.4"
fern = "0.5"
chrono = "0.4.6"
