-- Your SQL goes here
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE keys (
  id SERIAL PRIMARY KEY,
  key UUID UNIQUE NOT NULL,
  updated_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE players (
  id INTEGER NOT NULL,
  key_id INTEGER REFERENCES keys(id),
  name VARCHAR NOT NULL,
  score SMALLINT NOT NULL DEFAULT 0,
  updated_on TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id, key_id)
);
